[project]
name = "mcp-srv-insight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "insightface>=0.7.3",
    "mcp>=1.9.3",
    "onnxruntime>=1.22.0",
    "openai-agents>=0.0.17",
]
